coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        enabled: yes
        target: 90%
        threshold: 2%
    patch:
      default:
        enabled: yes
        target: 60%
